// JournalWidgetStore.swift
// ApinWidget
//
// Builds the widget extension's own `ModelContainer` against the shared App Group
// container so `ApinWidgetProvider` can read the same journal store as the `Apin` app
// target. Widget extensions run in a separate sandboxed process from the app, so
// SwiftData's default `ModelContainer(for:)` (which stores under the *target's own*
// private Application Support directory) would only ever see an empty store here --
// pointing both targets' `ModelConfiguration` at the same file inside a shared App
// Group container is what actually makes the data visible to the widget.
//
// STATUS (T16): the `ApinWidget` extension side of this wiring (this file, plus the
// `com.apple.security.application-groups` entitlement on the `ApinWidgetExtension`
// target in `project.yml`) is fully set up. The `Apin` app target also has the matching
// App Group entitlement (`project.yml`).
//
// STATUS (T18): `Apin/ApinApp.swift`'s own `ModelContainer` now points at this exact same
// App Group container/filename (see its `appGroupIdentifier`/`storeFileName` constants,
// duplicated there and documented to be kept in sync with this file), closing the gap left
// above -- this store now resolves to the app's real journal data, not an empty store, on
// any build/signing environment where the App Group entitlement actually resolves. T18 also
// layered CloudKit sync onto the app's `ModelConfiguration`
// (`cloudKitDatabase: .automatic`); this file's `ModelConfiguration(url:)` call already
// defaults to the same `cloudKitDatabase: .automatic` (SwiftData's own default parameter
// value), so no code change was needed here for that part -- see `project.yml` for the
// matching iCloud entitlement added to this target so it can open that store without a
// mismatched-capability error on a real device.
//
// NOTE: on the iOS Simulator, `containerURL(forSecurityApplicationGroupIdentifier:)`
// resolution is not strictly gated by code-signing entitlements the way it is on a real
// device (observed empirically while writing `ApinWidgetTests`) -- a build/run that
// "just works" in Simulator is not sufficient evidence the App Group is wired correctly
// for a real device; that needs on-device verification (see T18 completion notes in
// tasks/task-graph.md for what a human with Xcode + a real Apple Developer account needs
// to do to complete that verification, including the CloudKit half).

import ApinCore
import Foundation
import SwiftData

enum JournalWidgetStore {
    /// Must match the App Group configured in both targets' entitlements
    /// (`Apin/Apin.entitlements`, `ApinWidget/ApinWidget.entitlements`, generated by
    /// XcodeGen from `project.yml`).
    static let appGroupIdentifier = "group.com.kv.apin"

    /// Shared store filename. If/when `Apin/ApinApp.swift` is updated to opt into App
    /// Group storage (see this file's header), it must point its `ModelConfiguration` at
    /// this exact file inside the same App Group container for the two targets to
    /// actually share data.
    static let storeFileName = "ApinJournal.sqlite"

    /// Builds a `ModelContainer` for the shared store, or `nil` if the App Group
    /// container isn't reachable (e.g. entitlement/provisioning not resolved in this
    /// build environment). Callers must treat `nil` as "no data available" and fall back
    /// to the widget's empty state -- never crash/force-try here, since this runs in a
    /// widget extension process with no user-facing way to recover from a fatal error.
    ///
    /// Intentionally `nonisolated`/synchronous (no actor hop): `TimelineProvider`'s
    /// `getSnapshot`/`getTimeline` completion handlers are plain, non-`Sendable`
    /// closures, so this is called and returns within the same execution context that
    /// received them rather than crossing into `@MainActor` via `Task`, which trips
    /// Swift 6 strict-concurrency "sending risks a data race" diagnostics for those
    /// closures. Nothing here (`ModelContainer`/`ModelContext` construction plus an
    /// immediate, synchronous fetch) needs to outlive this single call.
    static func makeModelContainer() -> ModelContainer? {
        guard let groupContainerURL = FileManager.default.containerURL(
            forSecurityApplicationGroupIdentifier: appGroupIdentifier
        ) else {
            return nil
        }

        let storeURL = groupContainerURL.appendingPathComponent(storeFileName)
        let configuration = ModelConfiguration(url: storeURL)

        return try? ModelContainer(for: JournalEntry.self, configurations: configuration)
    }
}
